config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'foods#index', as: 'home'
  resources :users, only: %i[index show] do
    resources :foods
    resources :shopping_lists, only: %i[index show]
    resources :recipe_foods
    resources :recipes do
      resources :recipe_foods
    end
  end
  get 'public_recipes', to: 'recipes#public_recipes'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all

      can :edit, Recipe, user: user
      can :update, Recipe, user: user
      can :manage, Recipe, user: user

      can :manage, Food, user: user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def total_price
    foods.sum(&:price)
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, :food_id, presence: true

  def total_price
    quantity * food.price
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :foods

  validates :name, presence: true

  private

  def set_default_role
    update(role: 'user')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = current_user
    @foods = current_user.foods.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = current_user.foods.new
  end

  def create
    @food = current_user.foods.create(food_params)
    if @food.save
      redirect_to user_foods_path
    else
      render :new
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    @food.destroy
    redirect_to user_foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = current_user.recipes.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = @recipe.recipe_foods.create(recipe_foods_params)
    if @recipe_foods.save
      flash[:notice] = 'Recipe food is added!'
    else
      'Recipe foods failed to add!'
    end
    redirect_to user_recipe_path(id: @recipe_foods.recipe_id)
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    flash[:notice] = if @recipe_food.update(params.require(:recipe_food).permit(:food_id, :quantity))
                       'Food updated successfully!'
                     else
                       'Food was not updated!'
                     end
    redirect_to user_recipe_path(id: @recipe_food.recipe_id)
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = @recipe.recipe_foods.find(params[:id])
    @recipe_foods.destroy
    flash[:notice] = 'Recipe food has been removed from recipe!'
    redirect_to user_recipe_path(id: @recipe.id)
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_foods_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.where(id: params[:id]).includes(:recipe_foods).take
    @recipe_foods = @recipe.recipe_foods
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(params.require(:recipe).permit(:public))
  end

  def public_recipes
    @recipes = Recipe.where({ public: true }).order(created_at: :desc).includes(:user)
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    flash[:notice] = 'Recipe is Created!' if @recipe.save
    redirect_to user_recipes_path
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize! :destroy, @recipe
    @recipe.destroy
    flash[:notice] = 'Recipe has been destroyed!'
    redirect_to user_recipes_path
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @recipe = Recipe.where(id: params[:id]).includes(:recipe_foods).take
    @total = @recipe.recipe_foods.map(&:total_price).sum
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/index.html.erb
<div class="foods d-flex mx-auto p-5 w-75 flex-column align-items-center">
    <div class=" align-self-end">
        <%= link_to new_user_food_path(@user.id) do%>
            <button class="btn btn-primary">Add Food</button>
        <% end %>
    </div>
<table class="table table-striped table-hover table-bordered align-middle table-sm my-5">     
        <thead class="table-dark">

            <th scope="col">Foods</th>
            <th scope="col">Measurement unit</th>
            <th scope="col">Unit price</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>

            <% @foods.each do |food| %>
              <tr>
              <td><%= food.name %></td>
              <td><%= food.measurement_unit %></td>
              <td><%= food.price %></td>
              <td class="d-flex justify-content-center">
                  <%= button_to user_food_path(current_user, food), method: :delete, class: "btn btn-danger btn-sm m-1 ps-3 pe-3" do %>
                      </span>Delete</span>
                  <% end %>
              </td>
          </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/foods/new.html.erb
<section class="new-food d-flex flex-column align-items-center justify-content-center ">
<h2 class="text-secondary mt-4">Add New Food</h2>
<%= form_with(model: @food, url: { action: "create" }) do |form| %>
<div class="group-form">
    <%= form.label :name %><br />
    <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control"%>
</div>

<div class="group-form my-2">
    <%= form.label :"Measurement unit" %><br />
    <%= form.text_field :measurement_unit, autofocus: true, autocomplete: "measurement_unit", class: "form-control" %>
</div>

<div class="group-form">
    <%= form.label :"Price" %><br />
    <%= form.number_field :price, in: 1.0..20.0, step: 0.5, class: "form-control" %>
</div>
<%= form.submit "Add new food", class: "btn btn-primary my-3 align-self-end btn-submit" %>
</div> 
<% end %> 

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
      <%= render partial: 'shared/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipe_foods/edit.html.erb
<section class="d-flex flex-column align-items-center justify-content-center p-5">

<h2 class="text-secondary p-4">Edit Recipe food</h2>

<%= form_with model: @recipe_food, url: { action: "update"}, local: true do |form| %>

  <div class="field mt-3">
    <%= form.label :food, class: "label pb-2" %>
     <div class="select-option">
        <%= form.select :food_id, current_user.foods.collect {|food| [food.name, food.id] }, { include_blank: true}, class: "form-control" %>
     </div>
  </div>
  <div class="field mt-3">
   <%= form.label :quantity, class: "label pb-2"  %>
    <div class="quality">
      <%= form.number_field :quantity, class: "input", required: true, min: 1, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit  "Edit recipe food", class: "btn btn-primary my-3" %>
  </div>
<% end %>

</section>

app/views/recipe_foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipe Foods</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= link_to 'Show', recipe_food %></td>
        <td><%= link_to 'Edit', edit_recipe_food_path(recipe_food) %></td>
        <td><%= link_to 'Destroy', recipe_food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe Food', new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<div class="d-flex flex-column align-items-center justify-content-center p-5">
<h2 class="text-secondary p-4">Add food</h2>
  <%= form_with model: @recipe_food, url: { action: "create" } do |form| %>
    <div class="field mt-3 mb-2">
      <%= form.label :food, class: "label pb-2" %>
      <div class="select-option">
          <%= form.select :food_id, current_user.foods.collect {|food| [food.name, food.id] }, { include_blank: true}, class: "form-control" %>
      </div>
    </div>
    
    <div class="">
      <%= form.label :quantity, class: "label pb-2 " %>
      <div>
        <%= form.number_field :quantity, required: true, min: 0, class: "form-control input" %>
      </div>
    </div>

    <div>
      <%= form.submit class: "btn btn-primary mt-3" %>
    </div>
  <% end %>
</div>

app/views/recipe_foods/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_recipe_food_path(@recipe_food) %> |
<%= link_to 'Back', recipe_foods_path %>

app/views/recipes/_form.html.erb
<% if recipe.errors.present? %>
  <div class="errors notification is-danger is-light">
    <h3 class="title is-5"><%= pluralize(recipe.errors.count, "error") %> Cannot save this recipe:</h3>
    <ul>
      <% recipe.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with url: user_recipes_path, model: @recipe do |form| %>
  <div class="mb-3">
    <%= form.label :name, { class: "form-label"} %>
    <%= form.text_field :name, { class: "form-control", required: true, placeholder: "Please enter recipe name", value: nil } %>
  </div>

  <div class="mb-3">
    <%= form.label :preparation_time, { class: "form-label"} %>
    <%= form.text_field :preparation_time, { class: "form-control", required: true, placeholder: "How long is the preparation?", value: nil } %>
  </div>

  <div class="mb-3">
    <%= form.label :cooking_time, { class: "form-label"} %>
    <%= form.text_field :cooking_time, { class: "form-control", required: true, placeholder: "How long is the cooking?" } %>
  </div>

  <div class="mb-3">
    <%= form.label :description, { class: "form-label"} %>
    <%= form.text_area :description, { class: "form-control", required: true, placeholder: "Describe the process please" } %>
  </div>

  <div>
    <%= form.check_box :public %>
    <%= form.label :public %>
  </div>

  <div>
    <%= form.submit "Create Recipe", class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<section class="flex-column d-flex  w-75 m-auto mt-3">
<div class="align-self-end mx-5 my-3"><%= link_to 'Create a new Recipe', new_user_recipe_path, class: "btn btn-primary btn-sm btn-block my-1" %></div>
<div class="container h-100">

  <div class="columns is-flex-direction-column is-align-items-center">
    <% @recipes.each do |recipe| %>
      <div class="border border-muted d-flex ml-5 p-2 rounded" >
  <div class="columns w-25 p-1">
    <h2 class="p-2">
      <%= link_to recipe.name, user_recipe_path(current_user, recipe), class: "text-primary" %>
    </h2>
    <% if can? :destroy, recipe %>
      
        <%= link_to "Remove", user_recipe_path(current_user, recipe), method: :delete, data: { confirm: "Do you really want to delete this recipe?" }, class: "btn btn-outline-danger btn-sm mt-2 text-decoration-none mx-2" %>
    <% end %>
  </div>
  <div class="w-50 p-4">
    <p class="w-100 "><%= recipe.description %></p>
  </div>
</div>
<br/>
    <% end %>
  </div>
</div>
</section>

app/views/recipes/new.html.erb
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
           <div class="card-body p-5">
              <h3 class="title text-center">New Recipe</h3>

                 <%= render 'form', recipe: @recipe %>
            </div>
        </div>
       </div>
    </div>
    <%= link_to 'Back to Create New Recipe', user_recipes_path, class: "btn btn-primary btn-sm btn-block ml-4" %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="container border mt-4">
  <h2 class="title has-text-centered my-4">
   Public Recipes
  </h2>
  <% @recipes.each do |recipe| %>
    <div class="row justify-content-md-center my-4">
      <div class="row w-50">
        <div class="col-md-6 p-2">
          <h2><%= link_to recipe.name, user_recipe_path(current_user, recipe), class: "text-decoration-none" %></h2>
          <p>By: <%= recipe.user.name %></p>
        </div>
        <div class="col-md-6 p-2">
        <p>Total food items: <%= recipe.recipe_foods.size %></p>
        <p>Total price: <%= number_to_currency(recipe.total_price)%></p>
        </div>
    </div>
   </div>
    <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-10 col-lg-9 col-xl-8">
        <div class="card shadow-2-strong " style="border-radius: 1rem;">
          <div class="card-body p-2 text-center">
            <h1><%= @recipe.name %></h1>

            <div class="d-flex flex-column">

              <div class="row">
                <div class="col-md-6">
                  <p>Preparation time: <%= @recipe.preparation_time %></p>
                  <p>Cooking time: <%= @recipe.cooking_time %></p>
                  <div><%= @recipe.description %></div>
                </div>

                <div class="col-md-6">
                  <% if can? :update, @recipe %>
                  <%= form_with model: @recipe, url: user_recipe_path(@recipe), method: :patch, local: true do |form| %>
                    <div class="custom-control custom-switch">
                    <%= form.check_box :public, class: "custom-control-input", id: "customSwitch1" %>
                      <label class="custom-control-label" for="customSwitch1">Public</label>
                    </div>
                    <div class="actions btn btn-">
                         <%= form.submit "Submit status" %>
                    </div>
                   <% end %>
                  <% end %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 my-5">
                <%= link_to 'shopping list', user_shopping_lists_path(id: @recipe), class: "btn btn-primary" %>
                </div>
                <div class="col-md-6 my-5">
                  <% if can? :update, @recipe %> 
                    <%= link_to "Add Food", new_user_recipe_recipe_food_path(current_user, @recipe), class: "btn btn-primary btn-lg"%>
                  <% end %>
                </div>
              </div>     
              <div class="border-top border-secondary">
              </div>
              <br/>
              <table class="table table-striped table-hover table-bordered align-middle table-sm my-5">     
              <thead class="table-dark">

                  <th scope="col">Foods</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Value</th>
                  <th scope="col">Actions</th>
                  </tr>
              </thead>
              <tbody>

                <% @recipe_foods.each do |recipe_food| %>
                  <tr>
                    <td><%= recipe_food.food.name %></td>
                    <td><%= recipe_food.quantity %><%= recipe_food.food.measurement_unit %></td>
                    <td><%= number_to_currency((recipe_food.food.price).to_i * (recipe_food.quantity).to_i)%></td>
                    <td class="d-flex justify-content-center">
                        <%= button_to "Delete", user_recipe_recipe_food_path(current_user, @recipe, recipe_food), method: :delete, data: { confirm: 'Are you sure?' }, class: "r-food-btn btn btn-danger" %>
                        <%= link_to "Edit", edit_user_recipe_recipe_food_path(current_user, @recipe, recipe_food), class: "btn btn-primary mx-2 r-food-btn" %>
                    </td>
                  </tr>
                  <% end %>
              </tbody>
          </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-default">
  <h1 class="navbar-brand">Recipes</h1>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li><%= link_to "Home (Foods)", home_path %></li>
      <li class="nav-item ms-2">
              <%= link_to "Recipes", user_recipes_path(current_user) %>
            </li>
            <li class="nav-item ms-2">
              <%= link_to "Public recipes", public_recipes_path %>
            </li>
        <li class = "nav-list ms-2">
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        </li>
        <li class = "nav-list ms-2">
          <%= link_to "Edit Profile", edit_user_registration_path %>
        </li>
      <% else %>
        <li class = "nav-list mx-2">
          <%= link_to "Log In", new_user_session_path %>
        </li>
        <li class = "nav-list">
          <%= link_to "Sign Up", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shopping_lists/index.html.erb
<div class="container d-flex flex-column align-items-center p-4">

<h1  class="text-secondary align-center mb-3">Shopping list</h1>
  <div class="d-flex justify-content-between container w-75">
    <p class="h5 text-secondary">Amount of food to buy: <%= @recipe.recipe_foods.size%></p>
    <p class="h5 text-secondary">Total value of food needed: <%= number_to_currency(@total)%></p>
  </div>

  <table class="table w-50"">
    <% if @recipe.recipe_foods.any? %>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    <% end %>
      <% @recipe.recipe_foods.each do |food| %>
        <tr>
          <td><%= food.food.name%></td>
          <td><%= food.quantity%> <%= food.food.measurement_unit%></td>
          <td><%= number_to_currency(food.food.price*food.quantity)%></td>
        </tr>
      <% end %>
  </table>

    <button class = "btn">
  <%= link_to 'Back to my recipe', user_recipe_path(current_user, @recipe), class: "btn btn-primary" %>
  </button>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>